services:
  db:
    image: postgres:15
    container_name: app-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgrespassword}
      POSTGRES_DB: ${POSTGRES_DB:-nine_now}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-postgres}']
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:postgrespassword@db:5432/nine_now?schema=public
      - RESEND_API_KEY=${RESEND_API_KEY}
      - NODE_ENV=development
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3000'
    command: sh -c "npx prisma migrate deploy && npm run dev"

volumes:
  postgres_data:
