import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import StyledComponentsRegistry from '@/lib/registry'
import { getCurrentSession } from '@/lib/session'
import LogoutButton from '@/components/auth/LogoutButton'
import Link from 'next/link'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const { user } = await getCurrentSession()

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="h-20">
          {user ? (
            <LogoutButton>Logout</LogoutButton>
          ) : (
            <Link className="p-4 bg-slate-300" href="/login">
              Login Here
            </Link>
          )}
        </header>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  )
}
