import { getCurrentSession } from '@/lib/session'
import Header, { HeaderGradient } from '@/components/layout/header'
import Footer from '@/components/layout/footer'
import { Provider } from 'jotai'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function HomeLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { user } = await getCurrentSession()
  console.log(user)
  return (
    <div className="flex flex-col min-h-[100svh]">
      <Provider>
        <HeaderGradient />
        <Header
          user={user ? { givenName: user.givenName, id: user.id } : user}
        />
        <main className="relative z-10">{children}</main>
        <Footer
          user={user ? { givenName: user.givenName, id: user.id } : user}
        />
      </Provider>
    </div>
  )
}

// Header height for later reference
// mt-[80px] xl:mt-[112px]
