name: Build and Push Docker Image

on:
  pull_request:
    branches: [staging]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: 715841333383.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: streaming-service
          IMAGE_TAG: ${{ github.sha }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          docker build \
            --build-arg DATABASE_URL=$DATABASE_URL \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -f Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update Dockerrun.aws.json with image tag
        run: |
          sed -i "s/:latest/:${{ github.sha }}/g" Dockerrun.aws.json

      - name: Zip Dockerrun.aws.json
        run: zip Dockerrun.zip Dockerrun.aws.json

      - name: Upload Dockerrun.zip to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp Dockerrun.zip s3://elasticbeanstalk-us-east-1-715841333383/Dockerrun.zip

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name streaming_service_clone \
            --version-label ${{ github.sha }} \
            --source-bundle S3Bucket=elasticbeanstalk-us-east-1-715841333383,S3Key=Dockerrun.zip

          aws elasticbeanstalk update-environment \
            --application-name streaming_service_clone \
            --environment-name Streamingserviceclone-env \
            --version-label ${{ github.sha }}
