name: Restrict PRs to Main and Staging

on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Information
        run: |
          echo "Target branch: ${{ github.base_ref }}"
          echo "Source branch: ${{ github.head_ref }}"

      - name: Check Base Branch
        run: |
          if [[ "${{ github.base_ref }}" == "main" ]]; then
            if [[ "${{ github.event.pull_request.head.ref }}" != "staging" ]]; then
              echo "Pull requests to 'main' are only allowed from 'staging'."
              exit 1
            fi
          elif [[ "${{ github.base_ref }}" == "staging" ]]; then
            if [[ "${{ github.event.pull_request.head.ref }}" != "develop" ]]; then
              echo "Pull requests to 'staging' are only allowed from 'develop'."
              exit 1
            fi
          fi
